// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUsmg5oRnc_fPnOt5rGvwdDB_HWgHs3Ek',
    appId: '1:577971167998:web:08bfa44eefe5f6c2eebbaf',
    messagingSenderId: '577971167998',
    projectId: 'helloworld-948fc',
    authDomain: 'helloworld-948fc.firebaseapp.com',
    storageBucket: 'helloworld-948fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd40mTS1ybj9fpSZCDruB8_J3jiqAtzHw',
    appId: '1:577971167998:android:9d593c6b9fc095f2eebbaf',
    messagingSenderId: '577971167998',
    projectId: 'helloworld-948fc',
    storageBucket: 'helloworld-948fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbS6MFG8vLwqBFg7HdI_RVUfQXaz0AsC4',
    appId: '1:577971167998:ios:9cfd3a9073025d26eebbaf',
    messagingSenderId: '577971167998',
    projectId: 'helloworld-948fc',
    storageBucket: 'helloworld-948fc.firebasestorage.app',
    iosBundleId: 'com.example.studyPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbS6MFG8vLwqBFg7HdI_RVUfQXaz0AsC4',
    appId: '1:577971167998:ios:9cfd3a9073025d26eebbaf',
    messagingSenderId: '577971167998',
    projectId: 'helloworld-948fc',
    storageBucket: 'helloworld-948fc.firebasestorage.app',
    iosBundleId: 'com.example.studyPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUsmg5oRnc_fPnOt5rGvwdDB_HWgHs3Ek',
    appId: '1:577971167998:web:0b80f620c003abfaeebbaf',
    messagingSenderId: '577971167998',
    projectId: 'helloworld-948fc',
    authDomain: 'helloworld-948fc.firebaseapp.com',
    storageBucket: 'helloworld-948fc.firebasestorage.app',
  );

}